Added multitenancy for request routing
snkeos/fhir-works-on-aws-routing pull request #1
Opened 2021-08-04 09:26 UTC by MarioDegen

Issue #, if available:

Description of changes:
Added routing middleware and factory, which is responsible for supporting url based multi tenancy.
It also includes access control, which verifies the tenant id of request and the allowed tenant id stored as claim in the access token.
The tenant id is forwarded to all necessary handlers, in addition for search a tenant SearchFilter is added to each search request, which is performed on the elastic search.
Added tests for multi tenancy routing.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-09-01 09:12 UTC, ilyash-b requested changes
See comments

2021-09-01 09:12 UTC, ilyash-b commented on sampleData/r4FhirConfigNoGeneric.ts
> +    },
`multiTenancyOptions` is called `multiTenancyConfig` in `interface FhirConfig`.

Additionally, in the interface, `useTenantSpecificUrl` and `tenantIdClaimPath` are not optional but are also not specified here.

Same issues in other config files.

![Screen Shot 2021-08-31 at 16 37 55](https://user-images.githubusercontent.com/34807039/131513088-1cc48ad1-5cc3-484d-b0f0-bfcbf1e7bd47.png)

2021-09-01 09:12 UTC, ilyash-b commented on src/router/__mocks__/mainRouteTestServer.ts
> +        }
Can be simpler:

```suggestion
            // remove try and catch

            if (requestInformation.resourceType !== resourceType) {
                next(new InvalidResourceError('The request info must contain a resource type'));
                return;
            }

            res.locals.userIdentity = practitionerTenantsDecoded;
            next();
```

![Screen Shot 2021-08-31 at 16 55 49](https://user-images.githubusercontent.com/34807039/131515637-7082da59-87cb-4acd-907d-73a3e4105ea6.png)

2021-09-01 09:12 UTC, ilyash-b commented on src/router/__mocks__/mainRouteTestServer.ts
> +export function createJSON(resourceType: string, tenantId?: string, resourceId?: string) {
Misnamed. `createJSON` returns data structure, not JSON.

2021-09-01 09:12 UTC, ilyash-b commented on src/router/__mocks__/mainRouteTestServer.ts
> +        tenantId: tenantId === undefined ? 'NONE' : tenantId,
Please consider simpler `tenantId || 'NONE'` instead of `tenantId === undefined ? 'NONE' : tenantId`

2021-09-01 09:12 UTC, ilyash-b commented on src/router/__mocks__/mainRouteTestServer.ts
> +        }),
This code repeats 6 times and another 3 times with the slightest change: different resource id. Please factor out.

2021-09-01 09:12 UTC, ilyash-b commented on src/router/bundle/bundleGenerator.ts
> +        tenantUrl?: string,
It's not a URL, please rename. I assume it's tenant ID.

2021-09-01 09:12 UTC, ilyash-b commented on src/router/bundle/bundleHandlerInterface.ts
> +
Extra empty line

2021-09-01 09:12 UTC, ilyash-b commented on src/router/handlers/resourceHandler.ts
> +            searchFilters.push(tenantIdSearchFilter);
Consider moving this into `authService.getSearchFilterBasedOnIdentity` (called few lines above). Sounds like it logically belongs there. Also, this will eliminate code duplication (here and the other place is in `rootHandler.ts`)

2021-09-01 09:12 UTC, ilyash-b commented on src/router/routes/createMainRoute.ts
> +}
Consider eliminating this file. It only exports one small function.

2021-09-01 09:12 UTC, ilyash-b commented on src/router/routes/mainRoute.test.ts
> +describe('Regression: Routing with out multi tenancy: POST, PUT, PATCH, DELETE,GET /Patient', () => {
* Typo. Should be `without`
* Missing space before `GET`

2021-09-01 09:12 UTC, ilyash-b commented on src/router/routes/mainRoute.test.ts
> +            });
* Similar code with minor variations repeats several times. Please factor out.
* `'9876'` should be `resourceId`?

2021-09-01 09:12 UTC, ilyash-b commented on src/router/routes/mainRoute.test.ts
> +    it(`Post: /${resourceType} should return 201.`, async done => {
Confusing mix of `async` and usage of callback (`done`).

2021-09-01 09:12 UTC, ilyash-b commented on src/router/routes/mainRoute.ts
> +        RouteHelper.setMergeParams(true);
Can whole `mergeParams` passing be simplified somehow?

2021-09-01 09:12 UTC, ilyash-b commented on src/router/routes/routeHelper.ts
> +        if (RouteHelper.extractResourceUrlFn !== undefined) {
Defaulting `extractResourceUrlFn` to identity function would eliminate the if.

2021-09-01 09:12 UTC, ilyash-b commented on src/router/routes/tenantBaseMainRoute.ts
> +function validateTenantBaseUrl(tenantIdIndex: int, resourceTypeIndex: int, verb: string, urlPath: string): boolean {
Can we eliminate this function in favor of express handling the routes?

2021-09-01 09:12 UTC, ilyash-b commented on src/router/routes/tenantBaseMainRoute.ts
> +                            throw new UnauthorizedError('Unauthorized');
Please improve the error message

2021-09-01 09:12 UTC, ilyash-b commented on src/router/routes/tenantBaseMainRoute.ts
> +                        next();
Inserting `return;` after this line would simplify the code - less nesting.

2021-09-01 09:12 UTC, ilyash-b commented on src/router/routes/tenantBaseMainRoute.ts
> +                        if (tenants.includes(tenant) || req.params.tenantId === 'DEFAULT') {
`req.params.tenantId === 'DEFAULT'` - how this can be? We already had `if (req.params.tenantId === 'DEFAULT')` in the beginning.

2021-09-01 09:12 UTC, ilyash-b commented on src/router/routes/tenantBaseMainRoute.ts
> +            route = `/:tenantType(${this.options.tenantUrlPart})/:tenantId${resourceUrl}`;
* Why is it called `tenantType`?
* Why is it captured? I don't see any use of the captured `tenantType`.

2021-09-01 09:12 UTC, ilyash-b commented on src/router/routes/tenantBaseMainRoute.ts
> +                        const tenant: string =
Anything that includes `tenantAccessTokenClaimValuePrefix` can not be called `tenant`.

2021-09-01 09:12 UTC, ilyash-b commented on src/router/routes/tenantBaseMainRoute.ts
> +        if (this.options.tenantAccessTokenClaim !== undefined && !resourceUrl.includes('/metadata')) {
Maybe change logic to check any route that has non-default tenant ID in it instead? Sounds more straightforward to me. This would also eliminate `/metadata` check for example.

2021-09-01 09:12 UTC, ilyash-b commented on src/app.ts
> +    const mainRoute = createMainRoute(mainRouter, multiTenancyOptions);
`mainRoute` vs `mainRouter` in this file confusing, especially when some `mainRoute` were renamed to `mainRouter` while others were not.

2021-09-02 16:12 UTC, organom commented on src/router/routes/tenantBaseMainRoute.ts
> +                        throw new UnauthorizedError('Unauthorized wrong token claim');
We need to add an if to allow 'cdh/m2m' to continue independently of the tenantid. The scope to use (in this case 'cdh/m2m') shall be configurable

2021-09-06 09:03 UTC, MarioDegen commented on sampleData/r4FhirConfigNoGeneric.ts
> +    },
![image](https://user-images.githubusercontent.com/51999287/132190516-4c2722da-cc37-4719-a01e-8cea126a98c2.png)
FhirConfig was already updated to MultiTenancyOptions

2021-09-06 16:19 UTC, MarioDegen commented on sampleData/r4FhirConfigNoGeneric.ts
> +    },
MultiTenancyConfig is from an other branch not from Snke OS

2021-09-07 07:35 UTC, MarioDegen commented on src/router/bundle/bundleGenerator.ts
> +        tenantUrl?: string,
It is the sub url <tenantUrlPart>/tenantId, where <tenantUrlPart> is optional.

2021-09-07 08:13 UTC, MarioDegen commented on src/router/routes/tenantBaseMainRoute.ts
> +                        if (tenants.includes(tenant) || req.params.tenantId === 'DEFAULT') {
This is a leftover, will be removed :)

2021-09-07 09:46 UTC, MarioDegen commented on src/router/routes/tenantBaseMainRoute.ts
> +        if (this.options.tenantAccessTokenClaim !== undefined && !resourceUrl.includes('/metadata')) {
I think we cannot eliminate /metadata below any tenantId the /metadata endpoint must be accessible without checking the access token.

2021-11-09 10:40 UTC, MarioDegen commented on src/router/routes/routeHelper.ts
> +        if (RouteHelper.extractResourceUrlFn !== undefined) {
done

2022-01-28 12:34 UTC, ilyash-b requested changes
Try using https://nodejs.org/docs/latest-v12.x/api/async_hooks.html#async_hooks_class_asynclocalstorage

Most comments will probably be out of date if async hooks used.

2022-01-28 12:34 UTC, ilyash-b commented on src/router/__mocks__/mainRouteTestServer.ts
> +function handleAuth(mainRouter: express.Router, resourceType: string) {
Better name: `setupAuthMiddleware`

2022-01-28 12:34 UTC, ilyash-b commented on src/router/__mocks__/mainRouteTestServer.ts
> +export function corsDataJson() {
This function does not return JSON. https://ilya-sher.org/2016/09/05/json-vs-data-structure/

`CORSHeaders` maybe.

2022-01-28 12:34 UTC, ilyash-b commented on src/router/__mocks__/mainRouteTestServer.ts
> +async function sendResponseNoResourceId(req: express.Request, res: express.Response) {
For consistency, should be `sendResponseWithoutResourceId`

2022-01-28 12:34 UTC, ilyash-b commented on src/router/__mocks__/mainRouteTestServer.ts
> +export function createMetaData() {
Function name inconsistent with `corsDataJson` - either use `create` or don't but consistently

2022-01-28 12:34 UTC, ilyash-b commented on src/router/__mocks__/mainRouteTestServer.ts
> +export function createResponseBody(resourceType: string, tenantId?: string, resourceId?: string) {
Use default parameters. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters

2022-01-28 12:34 UTC, ilyash-b commented on src/router/__mocks__/mainRouteTestServer.ts
> +let perRequestOverrideAccessTokenScopes: string[] = [];
It would be great to find a way around using global variables. Right now the tests wouldn't run correctly in parallel.

2022-01-28 12:34 UTC, ilyash-b commented on src/router/__mocks__/mainRouteTestServer.ts
> +    const mainRouter = express.Router();
Any particular reason to use `Router`? Why not `server.use(...)`?

2022-01-28 12:34 UTC, ilyash-b commented on src/router/routes/tenantBasedMainRouterDecorator.ts
> +    return new MainRouterDecorator(mainRouter);
Would `return mainRouter` work?

2022-01-28 12:34 UTC, ilyash-b commented on src/router/__mocks__/mainRouteTestServer.ts
> +    itemRouter.get('/:id/_history', RouteHelper.wrapAsync(sendResponseWithResourceId));
`RouteHelper.wrapAsync()` should be factored out

2022-01-28 12:34 UTC, ilyash-b commented on src/router/routes/tenantBasedMainRouterDecorator.ts
> +    private grantAccessForSpecificTenant(res: express.Response, tenantId: string) {
Misnamed. `grantAccessForSpecificTenant` sounds like operation and not a check.

2022-01-28 12:34 UTC, ilyash-b commented on src/router/routes/tenantBasedMainRouterDecorator.ts
> +            return false;
`return tenantAccessTokenClaimValues.includes(tenantAccessTokenClaimValueToTest)`

2022-01-28 12:34 UTC, ilyash-b commented on src/router/routes/routeHelper.ts
> +    }
Can this be simplified? I'm having hard time following the logic here.

2022-01-28 12:34 UTC, ilyash-b commented on src/app.ts
> +            if (req.method !== 'OPTIONS') {
I don't understand enough here. I'd like to hear why it was needed and was safe to move this if.

2022-01-28 12:34 UTC, ilyash-b commented on src/router/routes/tenantBasedMainRouterDecorator.ts
> +export class TenantBasedMainRouterDecorator extends MainRouterDecorator {
Can all of this be done shorter and cleaner using only express Router in a more straightforward manner?

2022-01-28 12:34 UTC, ilyash-b commented on src/router/routes/tenantBasedMainRouterDecorator.ts
> +// This function inspects the format of the base url path whether the tenant information is correctly placed.
What would happen without validation? What If here, like all other expressjs parts, the routes/handlers would be set and that's it?

2022-01-28 12:34 UTC, ilyash-b commented on src/router/bundle/bundleGenerator.ts
> +                    url: tenantUrl? baseUrl + `/${tenantUrl}` : baseUrl,
`tenantUrl` - it's not URL

2022-01-28 12:34 UTC, ilyash-b commented on package.json
> +    "fhir-works-on-aws-interface": "link:../fhir-works-on-aws-interface",
This will not be accepted by upstream.

TODO:

* revert the change here
* revert the associated `yarn.lock` part of this change
* make sure that all our builds execute `yarn link fhir-works-on-aws-interface` before `yarn install`
* for the above to work, we must run `yarn link` in the `fhir-works-on-aws-interface` repository first
* add related notes to our (not this repo) documentation

Related documentation about linking:
* https://classic.yarnpkg.com/en/docs/cli/link
* https://docs.npmjs.com/cli/v8/commands/npm-link

2022-01-28 12:34 UTC, ilyash-b commented on src/router/routes/errorHandling.ts
> +// TODO: resolve this issue without this workaround
Please do. This is very hard to review and unlikely to be accepted upstream.

2022-01-28 12:34 UTC, ilyash-b commented on src/router/routes/mainRouterDecorator.ts
> +import RouteHelper from './routeHelper';
Unused

2022-01-28 12:34 UTC, ilyash-b commented on src/router/routes/mainRouterDecorator.ts
> +    use(forwardedUrl: string, childRouter: Router): MainRouterDecorator {
Inconsistent use of `express.Router` and `Router`

2022-01-28 12:34 UTC, ilyash-b commented on src/router/routes/metadataRoute.ts
> +import RouteHelper from './routeHelper';
Unused

2022-01-28 12:34 UTC, ilyash-b commented on src/router/__mocks__/mainRouteTestServer.ts
> +}
Too similar, can be one function. You can use just `sendResponseWithResourceId()` for everything. if `id` does not exist, it will be `undefined` and will not be in resulting JSON.

2022-03-16 18:01 UTC, closed without merging